### ISSUE TITLE
Clothes lines don't render on server, chunk related

### ISSUE THREAD

**Issue by ttamttamS** [JamiesWhiteShirt/clothesline-fabric#13] opened 2020-08-10 19:17 UTC
It seems that clotheslines (the lines, the crank, and pulley part of the anchor) will not render in certain chunks. These chunks change sometimes after teleporting. The switch between rendered and unrendered happens along chunk lines. Connecting an unrendered anchor to a rendered one will render it, connecting two unrendered anchors leaves them both unrendered. This one is tricky because it is very hard to reproduce. I have not been able to reproduce it in singleplayer (not that it can't happen just that I couldn't make it happen). I do have many mods, I suspect immersive portals or lithium might not be playing nice because they mess with chunks. I imagine this report on its own isn't enough to resolve the issue, because of reproduction issues, so if you need any more info please let me know.

**Comment by JamiesWhiteShirt** [comment] 2020-08-10 19:32
The relation to chunks makes me think this is an issue on the server side. I have actually tested for compatibility with Lithium and even made Clothesline disable a small feature in it for compatibility, but I might have missed something.

I was unaware of this until now. Maybe I will stumble over it in testing some time.

**Comment by ttamttamS** [comment] 2020-08-10 20:37
I managed to reproduce this on singleplayer with just clothesline 0.2.0, fabric api 0.17.0, and immersive portals 0.26. On Fabric Loader 0.9.1
Just load up those three mods, start a flat world and fly around placing anchors until you see them stop rendering like in the gif.
![Peek 2020-08-10 16-32](https://user-images.githubusercontent.com/23565330/89828727-70bf1580-db27-11ea-8751-99d54f75c184.gif)

**Comment by JamiesWhiteShirt** [comment] 2020-08-15 13:45
I identified a likely conflict with Immersive Portals as the cause. We'll have to figure out a solution together before I do anything to resolve this.

**Comment by JamiesWhiteShirt** [comment] 2020-10-18 09:09
Seems to have been fixed on Immersive Portals' end.

**Closed as completed by JamiesWhiteShirt** 2020-10-18 09:09 UTC
