### ISSUE TITLE
Lighting bug

### ISSUE THREAD

**Issue by LemmaEOF** [JamiesWhiteShirt/clothesline-fabric#7] opened 2019-07-12 04:04 UTC
There seems to be a lighting issue with items on a clothesline. Using Clothesline 0.1.0, Fabric API 0.3.0+188, Minecraft 1.14.3
![2019-07-11_21 00 47](https://user-images.githubusercontent.com/6722691/61101612-45975d80-a41f-11e9-9a8e-4db59a65dc1f.png)

**Comment by JamiesWhiteShirt** [comment] 2019-07-12 20:36
Unable to reproduce with information provided. Likely a compatibility issue with any mods you have installed but not listed.

**Comment by LemmaEOF** [comment] 2019-07-12 21:16
Yeah, it's been weirdly on-and-off for me. I'll see if I can find a reliable reproduce.

**Comment by UpcraftLP** [comment] 2019-07-12 22:14
might be related to some (Block) Entity render not cleaning up the GL state?

**Comment by LemmaEOF** [comment] 2019-07-15 00:56
Possibly? The only blocks with BERs in view are clotheslines and vanillla chests, though.

**Comment by JamiesWhiteShirt** [comment] 2019-07-15 06:21
Technically clothesline doesn't use block entities or block entity renderers at all, but they render right after block entities and right before entities. It could still be affected by other renderers.

**Comment by RViper80** [comment] 2019-08-09 20:16
Seems to do with some blocks in... Oceans?  Swamps?  Have a world here that shows it fairly well.  They darken when a certain line of chunks renders along the direction of the andesite arrow.

[Clothesline Test.zip](https://github.com/JamiesWhiteShirt/clothesline-fabric/files/3487902/Clothesline.Test.zip)

MC 1.14.4, Fabric 0.4.8 b 158, Clothesline 0.1.0, Fabric API 0.3.1 b 208.
Edit:  /tp @p 29 99 -220

**Comment by JamiesWhiteShirt** [comment] 2019-08-19 12:16
Many thanks for the world, @RViper80 ! I was able to track down the cause thanks to it. This issue is resolved in version 0.1.2.

**Closed as completed by JamiesWhiteShirt** 2019-08-19 12:16 UTC
